import re
b = "ayushi.jail@gmail.com"
match = re.search(r"[@]",b)
print(match)
match = re.search(r"\.",b)
print(match)
match = re.search(r"|.",b)
print(match)
match = re.findall(r"[i]",b)
print(match)
match = re.search(r"^a",b)
print(match)
match = re.search(r"$com",b)
print(match)
match = re.search(r"?a",b)
print(match)
match = re.search(r"+a",b)
print(match)
match = re.search(r"jail{1-2}",b)
print(match)
match = re.search(r"(j|g)ail",b)
print(match)
match = re.search(r'a\A')
print(match)
match = re.search(r'a\B')
print(match)